version: '3'

services:
  app:
    container_name: matters-api
    image: matters-server:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: ['npm', 'run', 'start:dev']
    env_file: ../.env
    volumes:
      - ..:/var/app
      - /var/app/node_modules
    depends_on:
      - db
      - redis
      - s3
      - elasticsearch
    ports:
      - '4000:4000'
  db:
    image: postgres:10
    container_name: matters-db
    environment:
      - POSTGRES_DB=matters-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  redis:
    image: redis
    container_name: matters-redis
    ports:
      - '6379:6379'
    restart: always
  s3:
    image: lphoward/fake-s3
    ports:
      - '4569:4569'
  elasticsearch:
    image: elasticsearch:6.5.4
    container_name: matters-search
    environment:
      - discovery.type=single-node
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  ? postgres_data
  ? es_data
